name: Build PyQt6 App


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller (Installer for each OS) 
      shell: bash
      run: |
        # Build once
        pyinstaller remote_zip_explorer.spec

        # OS-specific packaging
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          pip install pyinstaller
          pyinstaller-windows "dist/RemoteZipExplorer.exe" --output dist/RemoteZipExplorerInstaller.exe

        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          hdiutil create -volname "RemoteZipExplorer" -srcfolder dist -ov -format UDZO dist/RemoteZipExplorerInstaller.dmg

        else
          mkdir -p dist/installer
          cp -a "dist/RemoteZipExplorer" dist/installer/
          tar -czvf dist/RemoteZipExplorerInstaller.tar.gz -C dist/installer .
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: remote-zip-explorer-installer-${{ matrix.os }}
        path: |
          dist/RemoteZipExplorerInstaller*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/RemoteZipExplorerInstaller*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
